---
title: "Assignment 4"
author: "Avinash Ravipudi"
date: "2022-10-02"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Installing package
```{r}
#install.packages("lpSolve")
library("lpSolve") 
```

Objective Function

$$\text{Objective function: } Max \hspace{.2cm} Z = 420 (L_1+L_2+L_3) + 360 (M_1+M_2+M_3) + 300 (S_1+S_2+S_3)$$
Subject to constraints

$$L_1+M_1+S_1 \le 750$$
$$L_2+M_2+S_2 \le 900$$
$$L_3+M_3+S_3 \le 450$$

$$20L_1+15M_1+12S_1 \le 13000$$
$$20L_2+15M_2+12S_2 \le 12000$$
$$20L_3+15M_3+12S_3 \le 5000$$

$$L_1+L_2+L_3 \le 900$$
$$M_1+M_2+M_3 \le 1200$$
$$S_1+S_2+S_3 \le 750$$
Non Negativity Constraints
$$L_1,L_2,L_3,M_1,M_2,M_3,S_1,S_2,S_3 \ge 0$$
The above constraints can be written 

$$L_1+M_1+S_1+0L_2+0M_2+0S_2+0L_3+0M_3+0S_3 \le 750 $$

$$0L_1+0M_1+0S_1+L_2+M_2+S_2+0L_3+0M_3+0S_3 \le 900$$

$$0L_1+0M_1+0S_1+0L_2+0M_2+0S_2+L_3+M_3+S_3 \le 450$$
$$20L_1+15M_1+12S_1+0L_2+0M_2+0S_2+0L_3+0M_3+0S_3 \le 13000$$
$$0L_1+0M_1+0S_1+20L_2+15M_2+12S_2+0L_3+0M_3+0S_3 \le 12000$$
$$0L_1+0M_1+0S_1+0L_2+0M_2+0S_2+20L_3+15M_3+12S_3 \le 5000$$
$$L_1+0M_1+0S_1+L_2+0M_2+0S_2+L_3+0M_3+0S_3 \le 900$$

$$0L_1+M_1+0S_1+0L_2+M_2+0S_2+0L_3+M_3+0S_3 \le 1200$$

$$0L_1+0M_1+S_1+0L_2+0M_2+S_2+0L_3+0M_3+S_3 \le 750$$
Defining Objective Function and onstraints

```{r}
f1.obj <- c(420,360,300,420,360,300,420,360,300)
f1.con <- matrix(c(1,1,1,0,0,0,0,0,0,
                  0,0,0,1,1,1,0,0,0,
                  0,0,0,0,0,0,1,1,1,
                  20,15,12,0,0,0,0,0,0,
                  0,0,0,20,15,12,0,0,0,
                  0,0,0,0,0,0,20,15,12,
                  1,0,0,1,0,0,1,0,0,
                  0,1,0,0,1,0,0,1,0,
                  0,0,1,0,0,1,0,0,1), nrow = 9, byrow=T)

f1.dir <- c('<=',

           '<=',

           '<=',

           '<=',

           '<=',

           '<=',

           '<=',

           '<=',

           '<=')

```
Defining the constants f1.rhs

```{r}
f1.rhs <- c(750,900,450,13000,12000,5000,900,1200,750)
```

Calling lp function

```{r}
lp('max',f1.obj,f1.con,f1.dir,f1.rhs)
```

```{r}
lp('max',f1.obj,f1.con,f1.dir,f1.rhs)$solution
```



